master_tasks = [
    "prepare food",
    "serve the food",
    # "prepare breakfast (boiled_eggs)",
    # "prepare breakfast (fruit_salad)",
    # "prepare breakfast (toast)",
    # "prepare breakfast (cereal)",
    # "prepare breakfast (cake)",
    # "prepare breakfast (pizza)",
    # "prepare breakfast (noodles)",
    # "prepare breakfast (fried_chicken)",
    # "prepare breakfast (chips)",
    # "prepare lunch (rice)",
    # "prepare lunch (soup)",
    # "prepare lunch (lentil)",
    # "prepare lunch (cake)",
    # "prepare lunch (pizza)",
    # "prepare lunch (noodles)",
    # "prepare lunch (fried_chicken)",
    # "prepare lunch (chips)",
    # "prepare dinner (rice)",
    # "prepare dinner (soup)",
    # "prepare dinner (lentil)",
    # "prepare dinner (cake)",
    # "prepare dinner (pizza)",
    # "prepare dinner (noodles)",
    # "prepare dinner (fried_chicken)",
    # "prepare dinner (chips)",
    # "serve the food (boiled_eggs)",
    # "serve the food (fruit_salad)",
    # "serve the food (toast)",
    # "serve the food (cereal)",
    # "serve the food (cake)",
    # "serve the food (pizza)",
    # "serve the food (noodles)",
    # "serve the food (fried_chicken)",
    # "serve the food (chips)",
    # "serve the food (rice)",
    # "serve the food (soup)",
    # "serve the food (lentil)",
    # "serve a drink (water)",
    "serve a drink",
    "serve a drink (coke)",
    "serve a drink (energy_drink)",
    "serve a drink (juice)",
    "serve a drink (milk)",
    "serve a drink (water)",
    "prepare medicines",
    "wash the dishes",
    "wash dishes",
    "do the laundry",
    "do laundry",
    "prepare office clothes",
    "prepare casual clothes",
    "prepare gym clothes",
    "charge the electronic devices",
    "charge electronic devices",
    "prepare the office bag",
    "prepare office bag",
    "clean the room (kitchen)",
    "clean the room (bathroom)",
    "clean the room (bedroom)",
    "clean the room (livingroom)",
    "set up the office table",
    "throw away leftover food",
    "put remaining food in the fridge",
    "decorate the place",
    "dust electronic devices",
    "extinguish the fire",
]
