task_user_1 = [
    "clean the room (livingroom) (using vacuum cleaner)",
    "prepare breakfast (boiled eggs)",
    "set up the office table",
    "serve the food (boiled eggs) (location=office table)",
    "serve the drink (coffee) (location=office table)",
    "prepare lunch (sandwich)",
    "serve lunch (sandwich) (location=dining table)",
    "wash the dishes",
    "put remaining food in the fridge",
    "prepare dinner (rice)",
    "serve dinner (rice) (location=dining table)",
    "prepare medicines",
    "wash the dishes",
    "put remaining food in the fridge",
    "serve the food (mixed vegetables) (location=dining table)",
    "prepare medicines",
    "charge the electronic devices",
    "do the laundry",
    "prepare clothes (casual)",
    "prepare clothes (gym)",
    "prepare clothes (office)",
    "charge the electronic devices (cellphone)",
    "charge the electronic devices (laptop)",
    "prepare office bag",
    "clean the room (kitchen) (using vacuum cleaner)",
    "clean the room (bathroom) (using mop)",
    "prepare lunch (soup)",
    "serve the drink (milk) (location=dining table)",
    "serve the drink (tea) (location=dining table)",
]

task_user_2 = [
    "charge the electronic devices",
    "prepare clothes (party)",
    "serve breakfast (chips)",
    "put leftover food in the fridge",
    "decorate the place",
    "prepare clothes (party)",
    "serve the drink",
    "wash the dishes",
]
